# 配置文件

DAILY_TIME: 08:00 # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: 2020-02-03# 纪念日
CITY:宿州

BIRTHDAY:
  - 06-06

APP_ID: wx1571471450a832f0
APP_SECRET: c1dd95e4b45c163224f1ba17b85b1b8e

USER_ID: 
  - oQ91X6yd5cNeMBm7eElQra6dWAF4
  -oQ91X628_AtqMO4NX2m6ijI7-z38 # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: x8tVOEWsLL4jBNEOywelYr1kY8YTqMwgGXeJbg225HQ
